{% set name = "eval-type-backport" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eval_type_backport-{{ version }}.tar.gz
  sha256: d83ee225331dfa009493cec1f3608a71550b515ee4749abe78da14e3c5e314f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.7
  run_constrained:
    - {{ pin_subpackage("eval-type-backport", max_pin="x.x.x") }}
    
test:
  imports:
    - eval_type_backport
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: eval_type_backport
  - name: eval-type-backport
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("eval_type_backport", max_pin="x.x.x") }}
        - python >=3.7
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - eval_type_backport

about:
  home: https://github.com/alexmojaki/eval_type_backport
  summary: Like `typing._eval_type`, but lets older Python versions use newer typing features.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tasansal
    - alexmojaki
