{% set name = "eval_type_backport" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eval_type_backport-{{ version }}.tar.gz
  sha256: f0576b4cf01ebb5bd358d02314d31846af5e07678387486e2c798af0e7d849c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
  run_constrained:
    - {{ pin_subpackage("eval-type-backport", max_pin="x.x.x") }}

test:
  imports:
    - eval_type_backport
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: eval_type_backport
  - name: eval-type-backport
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("eval_type_backport", max_pin="x.x.x") }}
        - python >={{ python_min }}
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - eval_type_backport

about:
  home: https://github.com/alexmojaki/eval_type_backport
  summary: Like `typing._eval_type`, but lets older Python versions use newer typing features.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tasansal
    - alexmojaki
